import "../styles/global.css";
import Provider from "@components/provider/Provider";

export const metadata = {
  title: "Modern Login Page",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <Provider>
        <main>{children}</main>
      </Provider>
    </body>
  </html>
);

export default RootLayout;
